# sudo required for coveralls
sudo: required
language: rust
dist: trusty
cache: cargo

addons:
  apt:
    packages:
      - libssl-dev
rust:
  - stable
  - beta
  - nightly

script:
  - |
      cargo clean &&
      cargo build &&
      cargo test

after_success: |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      # Uncomment the following line for coveralls.io
      cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
    fi

matrix:
  allow_failures:
    - rust: nightly
